Support monospace formatting
matrix-org/matrix-appservice-irc pull request #1555
Opened 2022-04-18 15:49 UTC by progval

2022-09-22 11:58 UTC, jaller94 commented
@progval We need a [Sign Off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off) from you to accept this PR.

2022-09-22 17:01 UTC, jaller94 requested changes
Looks good, but Sign Off is missing.

2022-10-11 18:55 UTC, progval commented
Signed-off-by: Valentin Lorentz <progval plus git at progval dot net>

2022-10-25 08:44 UTC, Half-Shot approved these changes

2022-10-25 08:44 UTC, merged