Add new setup widget UI
matrix-org/matrix-appservice-irc pull request #1656
Opened 2023-01-23 17:22 UTC by justinbot

Following #1655 which added support for widgets authenticating with the Provisioning API, this PR adds a UI for configuring bridged rooms from within a widget:

![Screenshot 2023-01-23 at 11 53 49 AM](https://user-images.githubusercontent.com/20007954/214100472-5859b8f7-ea79-43b7-bde2-6594fd7fbf8e.png)

## Implementation
At a high level, the widget is just a static webpage which interacts with the Provisioning API to perform configuration.

More specifically, this takes the same approach as the [setup widgets in `matrix-hookshot`](https://github.com/matrix-org/matrix-hookshot/blob/main/web/BridgeAPI.ts), but implemented with the consideration that much of it is generic and could be refactored out into a package for reuse in other bridges.

### Provisioning API
This part of the implementation is relevant for any API using the `ProvisioningApi` class from `matrix-appservice-bridge`. Includes:
* Parsing widget query parameters.
* Widget API setup and obtaining an OpenID token.
* Exchanging the OpenID token for a session token, storing and checking validity of the session token.
* Instantiating a generic Provisioning API client.

### Frontend
The same approach for building a frontend with Vite could be taken for other bridges, as well as the handful of reusable UI components which have been implemented with Tailwindcss.

### IRC Bridge
The IRC Provisioning API client and the actual configuration UI are specific to this IRC Bridge.

## Demo

https://user-images.githubusercontent.com/20007954/214106268-bc953fac-041d-48ff-9298-a99b8d7e0a84.mov

2023-01-23 19:39 UTC, jaller94 commented on widget/src/IrcApp.tsx
> +            onChange={e => setChannelKey(e.target.value)}
useCallback to minimize DOM changes.

2023-01-23 19:44 UTC, jaller94 commented on widget/src/components/buttons/Danger.tsx
> +const Danger = (props: React.ComponentProps<'button'>) =>
To avoid the type cast below:
```suggestion
const Danger = (props: React.ComponentProps<'button'> & {className: string}) =>
```

2023-02-06 11:38 UTC, Half-Shot requested changes
This is actually looking amazing, you should be very proud of this work! I have a few minor concerns, but the bulk of this is great.

2023-02-06 11:38 UTC, Half-Shot commented on widget/src/IrcApp.tsx
> +        if (networks.servers.length > 0) {
My cheeky suggestion is that if the server length is 1 (which is true in nearly all cases), we should just render this as a readonly field. Something to make it look like not a dropdown.

2023-02-06 11:38 UTC, Half-Shot commented on widget/src/IrcApp.tsx
> +const pollLinkIntervalMs = 2000;
2s seems kinda high?

2023-02-06 11:38 UTC, Half-Shot commented on widget/src/IrcApp.tsx
> +        <Text.Title>Link a new channel</Text.Title>
I feel like we need some text here to explain the approval process etc.

2023-02-06 11:41 UTC, Half-Shot commented
One final thought @justinbot, can you write some documentation on this feature in the hosted docs. It can probably be similar to the hookshot ones. Thanks!

2023-02-07 09:03 UTC, Half-Shot approved these changes
Smashing, one note in the docs then this is ready to ship I feel :)

2023-02-07 09:03 UTC, Half-Shot commented on docs/setup_widget.md
> +/addwidget https://example.com/_matrix/provision/v1/static/?roomId=$matrix_room_id&widgetId=$matrix_widget_id
*where https://example.com is a public route to your IRC bridge's provisioning API

2023-02-08 16:02 UTC, merged