Make bridgeInfoState configuration reloadable
matrix-org/matrix-appservice-irc pull request #1681
Opened 2023-03-11 19:57 UTC by progval

This will be useful for tests in a future PR

2023-03-11 19:57 UTC, progval commented
Signed-off-by: Valentin Lorentz \<progval plus matrixsignoff at progval dot net\>

2023-04-05 17:00 UTC, Half-Shot requested changes

2023-04-12 13:39 UTC, Half-Shot commented on src/bridge/IrcBridge.ts
> +        }
Does `this.config.ircService.bridgeInfoState` need to be updated in here?

2023-04-26 11:06 UTC, Half-Shot approved these changes
LGTM, will merge in a bit.

2023-04-26 11:28 UTC, merged