Log when a channel is bridged/unbridged
matrix-org/matrix-appservice-irc pull request #1738
Opened 2023-06-05 21:21 UTC by Half-Shot

Fixes #1736

2023-06-06 10:07 UTC, Half-Shot commented
Guess which guy based his branch on the wrong parent.

< this guy

2023-06-06 17:44 UTC, AndrewFerr requested changes
Just one small nitpick request

2023-06-06 17:44 UTC, AndrewFerr commented on src/provisioning/Provisioner.ts
> +        req.log.info(`Provisioning unlink for room ${mappingLogId} (for ${userId})`);
Nitpick: for consistency, either remove the parentheses here, or add them to line 789.

2023-06-08 18:23 UTC, AndrewFerr approved these changes

2023-06-08 18:31 UTC, merged