Add a test to ensure that the irc client state doesn't bloat on VERSION
matrix-org/matrix-appservice-irc pull request #1753
Opened 2023-07-25 15:07 UTC by Half-Shot

Requires https://github.com/matrix-org/node-irc/pull/108

2023-07-25 15:18 UTC, tadzik requested changes

2023-07-25 15:18 UTC, tadzik commented on spec/e2e/pooling.spec.ts
> +    it.only('should store the IRC client state once', async () => {
```suggestion
    it('should store the IRC client state once', async () => {
```

2023-07-25 15:18 UTC, tadzik commented on spec/e2e/pooling.spec.ts
> +    it.only('should store the IRC client state once', async () => {
(There's some eslint rule for that)

2023-07-25 15:23 UTC, Half-Shot commented on spec/e2e/pooling.spec.ts
> +    it.only('should store the IRC client state once', async () => {
aha, `eslint-plugin-jest`

2023-07-28 08:59 UTC, tadzik approved these changes

2023-07-28 09:06 UTC, merged