Fix Redis <=6.2 throwing errors when trying to clear the command queue in pooling mode.
matrix-org/matrix-appservice-irc pull request #1763
Opened 2023-08-01 09:51 UTC by Half-Shot

Fixes #1761 

Ultimately the problem here is that we failed to specify a minimum Redis version. If you are using less than 6.2, you won't be able to clear the command stream effectively. To get around this for now, we're reverting to previous behaviour of just setting an absolute maximum message count for the stream when running on older Redis versions.

2023-08-01 10:10 UTC, tadzik requested changes
Some concerns. I like the refactoring!

2023-08-01 10:10 UTC, tadzik commented on src/pool-service/CommandReader.ts
> +        this.redis.info("Server")).split('\n').filter(v => !v.startsWith('#')).map(v => v.split(':', 2)
Ouch. Awkward that there's no easier way to do this.

2023-08-01 10:10 UTC, tadzik commented on src/pool-service/CommandReader.ts
> +            log.warn(`Unable to identify Redis version, assuming unsupported version`);
Perhaps we should also do this if parsing the server info failed for any reason.

2023-08-01 11:53 UTC, Half-Shot commented on src/pool-service/CommandReader.ts
> +        this.redis.info("Server")).split('\n').filter(v => !v.startsWith('#')).map(v => v.split(':', 2)
I was quite annoyed the library didn't parse this for us, but oh well.

2023-08-02 07:30 UTC, tadzik approved these changes

2023-08-02 08:32 UTC, merged